package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"

	"github.com/wilbertcoandssss/training-preweb/graph/model"
)

// InsertMedia is the resolver for the insertMedia field.
func (r *mutationResolver) InsertMedia(ctx context.Context, postID string, mediaURL []string) ([]*model.Media, error) {
	var insertedMedia []*model.Media

	for _, url := range mediaURL {
		newMedia := &model.Media{
			PostID:   postID,
			MediaURL: url,
		}

		if err := r.DB.Create(newMedia).Error; err != nil {
			return nil, err
		}

		insertedMedia = append(insertedMedia, newMedia)
	}

	return insertedMedia, nil
}

// GetAllMedia is the resolver for the getAllMedia field.
func (r *queryResolver) GetAllMedia(ctx context.Context, postID string) ([]*model.Media, error) {
	var media []*model.Media

	if err := r.DB.Where("post_id = ?", postID).Find(&media).Error; err != nil {
		return nil, err
	}

	return media, nil
}
